contact_links:
  - about: Ask a question or request support here
    name: Ask for Support
    url: >-
      https://github.com/MintNetwork/mint-blockchain/issues
  - about: Request a new feature or idea here
    name: Make a Request
    url: >-
      https://github.com/MintNetwork/mint-blockchain/pulls
  - about: Get support on the Mint Discord chat channels.
    name: Join the Discord support chat
    url: 'https://discord.gg/rAtQwUJ9Ac'